export const GET_BRIEF_SECTION_NEWS = 'GET_BRIEF_SECTION_NEWS';
export const BRIEF_SECTION_NEWS_IS_FETCHING = 'BRIEF_SECTION_NEWS_IS_FETCHING';
export const BRIEF_SECTION_NEWS_IS_ERROR_OCCURRED = 'BRIEF_SECTION_NEWS_IS_ERROR_OCCURRED';


export const GET_NEWS = 'GET_NEWS';
export const NEWS_ARE_FETCHING = 'NEWS_ARE_FETCHING';
export const NEWS_ERROR_OCCURRED = 'NEWS_ERROR_OCCURRED';
export const SET_NEWS_SEARCH_TERM = 'SET_NEWS_SEARCH_TERM';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';