export const LATEST_HEADLINES_IS_ERROR_OCCURRED = 'LATEST_HEADLINES_IS_ERROR_OCCURRED';
export const LATEST_HEADLINES_IS_FETCHING = 'LATEST_HEADLINES_IS_FETCHING';
export const GET_LATEST_HEADLINES = 'GET_LATEST_HEADLINES';
 

export const NEWS_ARE_FETCHING = 'NEWS_ARE_FETCHING';
export const NEWS_ERROR_OCCURRED = 'NEWS_ERROR_OCCURRED';
export const GET_NEWS = 'GET_NEWS';
export const SET_NEWS_PAGE_NUMBER = 'SET_NEWS_PAGE_NUMBER';
export const SET_NEWS_SEARCH_TERM = 'SET_NEWS_SEARCH_TERM';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';