export const LATEST_HEADLINES_IS_ERROR_OCCURRED = 'LATEST_HEADLINES_IS_ERROR_OCCURRED';
export const LATEST_HEADLINES_IS_FETCHING = 'LATEST_HEADLINES_IS_FETCHING';
export const GET_LATEST_HEADLINES = 'GET_LATEST_HEADLINES';

export const NEWS_BY_SEARCH_TERM_IS_ERROR_OCCURRED = 'NEWS_BY_SEARCH_TERM_IS_ERROR_OCCURRED';
export const NEWS_BY_SEARCH_TERM_IS_FETCHING = 'NEWS_BY_SEARCH_TERM_IS_FETCHING';
export const GET_NEWS_BY_SEARCH_TERM = 'GET_NEWS_BY_SEARCH_TERM';

export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';